version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=productosdb
      - MYSQL_USER=productos
      - MYSQL_PASSWORD=productos123
    ports:
      - "3306:3306"
    networks:
      - backend

  productos:
    build:
      context: ../Productos
    ports:
      - "8088:8080"
    volumes:
      - ./wallet:/app/wallet
    environment:
      - SPRING_APPLICATION_NAME=productos
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/productosdb
      - SPRING_DATASOURCE_USERNAME=productos
      - SPRING_DATASOURCE_PASSWORD=productos123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge