version: '3.8'
services:
  productos:
    build:
      context: ../Productos
    ports:
      - "8088:8080"
    volumes:
      - ./wallet:/app/wallet
    environment:
      - SPRING_APPLICATION_NAME=productos
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@kgrasril5bsgzi0i_high?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=ADMIN
      - SPRING_DATASOURCE_PASSWORD=FullStack-001
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - TNS_ADMIN=/app/wallet
    networks:
      - backend

networks:
  backend:
    driver: bridge